name: CI CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  # ============================
  # 1) CI JOB — CHECK DATABASE_URL
  # ============================
  # ============================
  # 2) DEPLOYMENT JOB — RUNS AFTER CI SUCCESS
  # ============================
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.93.105.151
          username: mclanduser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd apps/Webiste_Land
            git pull origin main
            npm install
            pm2 restart website_land
            ls -a

  # ============================
  # 3) VPN Check — RUNS AFTER Deploye and see the vpn is rinning or not
  # ============================
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Axios (test dependency)
        run: npm install axios

      - name: Set BASE_URL to live site
        run: |
          sed -i 's|http://localhost:3000|https://mclandpharma.com|g' test/vpn-test.js

      - name: Run VPN Tests
        run: |
          echo "Running VPN Test Suite..."
          node test/vpn-test.js
